services:
  caddy:
    image: caddy:2.8
    restart: always
    environment:
      SERVER_NAME: :80
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site/public_html:/var/www/html
      - caddy_data:/data
      - caddy_config:/config
  php:
    build: ./php
    restart: always
    volumes:
      - ./site/public_html:/var/www/html
    user: ${UID}:${GID}
  db1:
    image: mysql:5.7
    restart: always
    environment:
      TZ: Europe\Moscow
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: "0M{6lskj"
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "z5NxW9VP"
    volumes:
      # - db_data1:/var/lib/mysql
      - ./db_data1:/var/lib/mysql
    user: ${UID}:${GID}
  # db:
  #   image: postgres:16
  #   restart: always
  #   environment:
  #     POSTGRES_DB: "db"
  #     POSTGRES_USER: "user"
  #     POSTGRES_PASSWORD: "z5NxW9VP"
  #   volumes:
  #     - db_data:/var/lib/postgresql/data

volumes:
  caddy_data:
  caddy_config:
  db_data:
  db_data1:
